package com.wj.learnmvi.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wj.learnmvi.dao.bean.BtnInfo;
import com.wj.learnmvi.dao.bean.ModInfo;
import com.wj.learnmvi.dao.bean.PageInfo;
import com.wj.learnmvi.dao.bean.UserInfo;

import com.wj.learnmvi.dao.BtnInfoDao;
import com.wj.learnmvi.dao.ModInfoDao;
import com.wj.learnmvi.dao.PageInfoDao;
import com.wj.learnmvi.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig btnInfoDaoConfig;
    private final DaoConfig modInfoDaoConfig;
    private final DaoConfig pageInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final BtnInfoDao btnInfoDao;
    private final ModInfoDao modInfoDao;
    private final PageInfoDao pageInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        btnInfoDaoConfig = daoConfigMap.get(BtnInfoDao.class).clone();
        btnInfoDaoConfig.initIdentityScope(type);

        modInfoDaoConfig = daoConfigMap.get(ModInfoDao.class).clone();
        modInfoDaoConfig.initIdentityScope(type);

        pageInfoDaoConfig = daoConfigMap.get(PageInfoDao.class).clone();
        pageInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        btnInfoDao = new BtnInfoDao(btnInfoDaoConfig, this);
        modInfoDao = new ModInfoDao(modInfoDaoConfig, this);
        pageInfoDao = new PageInfoDao(pageInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(BtnInfo.class, btnInfoDao);
        registerDao(ModInfo.class, modInfoDao);
        registerDao(PageInfo.class, pageInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        btnInfoDaoConfig.clearIdentityScope();
        modInfoDaoConfig.clearIdentityScope();
        pageInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public BtnInfoDao getBtnInfoDao() {
        return btnInfoDao;
    }

    public ModInfoDao getModInfoDao() {
        return modInfoDao;
    }

    public PageInfoDao getPageInfoDao() {
        return pageInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
